### ISSUE TITLE
Strange black color in CapsuleTest

### ISSUE THREAD

**Issue by lyrachord** [Birdasaur/FXyz#12]
I found the CapsuleTest have a propblem:
change the loop max to 1, to keep just one Capsule object in the group,
and change the scene background to white color, because the problem is just black
Then the only capsule object will be rendered by only black color.
so strange!

Any idea? or I missed something?
Thanks

**Comment by Birdasaur** [comment]
Hey there!  I updated the CapsuleTest class as you described and I did get the same effect you see.  However it's not really a bug... just a coincidence on how JDub designed the lighting for the test.  In the test check out this code in the for loop:

```
            Color randomColor = new Color(r.nextDouble(), r.nextDouble(), r.nextDouble(), r.nextDouble());
            
            Capsule cap = new Capsule(randomRadius, randomHeight, randomColor);               
            cap.setEmissiveLightingColor(randomColor);
            cap.setEmissiveLightingOn(r.nextBoolean());
```

He doesn't actually add a PointLight or any AmbientLight objects.  He sets each Capsule to emit a light themselves.  So regardless of the randomColor, if you only have one Capsule object it will appear Black because there are no other capsules in the scene emitting light to colorize it.  I was able to prove that by simply adding a colored Point light to the root group

```            root.getChildren().add(new PointLight(Color.RED));  

![capsuletest](https://cloud.githubusercontent.com/assets/4649925/9854810/bdc53938-5ad8-11e5-9713-347d95223952.png)

So its actually a "Feature" !! :-p

**Comment by Birdasaur** [comment]
Try the changes I mentioned and if you think its cool we can close this issue.

**Comment by lyrachord** [comment]
Yes! Great!
So many thanks from the PointLight:)

**Comment by Birdasaur** [comment]
Awesome. Closing the issue.
If you have the time why don't you send me a message describing what you are trying to use FXyz for. We are always curious.  sean.mi.phillips@gmail.com

**Comment by lyrachord** [comment]
Thank you again.
OK, very hi to do mail.
